### ISSUE TITLE
useRestyle crashes in v2 as well

### ISSUE THREAD

**Issue by Nadimkhan120** [Shopify/restyle#140]
import {TouchableOpacity, View} from 'react-native';
import {
  useRestyle,
  spacing,
  border,
  backgroundColor,
  SpacingProps,
  BorderProps,
  BackgroundColorProps,
  composeRestyleFunctions,
} from '@shopify/restyle';

import {Text} from './Text';
import {Theme} from './theme';

const restyleFunctions = composeRestyleFunctions([
  spacing,
  border,
  backgroundColor,
]);
type Props = SpacingProps<Theme> &
  BorderProps<Theme> &
  BackgroundColorProps<Theme> & {
    onPress: () => void;
  };

export const Button = ({onPress, label, ...rest}: Props) => {
  const props = useRestyle(restyleFunctions, rest);

  return (
    <TouchableOpacity onPress={onPress}>
      <View {...props}>
        <Text variant="heading">{label}</Text>
      </View>
    </TouchableOpacity>
  );
};

 

TypeError: (0, _restyle.composeRestyleFunctions) is not a function. (In '(0, _restyle.composeRestyleFunctions)([_restyle.spacing, _restyle.border, _restyle.backgroundColor])', '(0, _restyle.composeRestyleFunctions)' is undefined)

**Comment by sbalay** [comment]
I've added a similar component to a project with restyle 2 and it doesn't seem to crash. This is a version of the component I've used:

```tsx
import {Text, View} from 'react-native'
import {
  useRestyle,
  spacing,
  border,
  backgroundColor,
  SpacingProps,
  BorderProps,
  BackgroundColorProps,
  composeRestyleFunctions,
} from '@shopify/restyle'
import {Theme} from 'shared/theme'

const restyleFunctions = composeRestyleFunctions([
  spacing,
  border,
  backgroundColor,
])

type Props = SpacingProps<Theme> &
  BorderProps<Theme> &
  BackgroundColorProps<Theme> & {label: string}

export const CustomText = ({label, ...rest}: Props) => {
  const props = useRestyle(restyleFunctions, rest)

  return (
    <View {...props}>
      <Text>{label}</Text>
    </View>
  )
}
```

Could you create and share a repo with the code and instructions to reproduce the crash you describe?

**Comment by obouchari** [comment]
I run into some issues as well after upgrading to v2. Followed upgrade instructions and I got the following error (see screenshots):
![CleanShot 2022-04-02 at 21 21 21](https://user-images.githubusercontent.com/4773811/161401666-83f2298c-eb62-4d27-9c1e-8a783d060dc1.png)
![CleanShot 2022-04-02 at 21 21 45](https://user-images.githubusercontent.com/4773811/161401674-c831cd57-d9dc-4f0f-b015-4e562a5b00fc.png)

Note that I didn't make any changes from the previous version except for upgrading to v2 and updating useRestyle (see screenshots)

Thank you in advance
